[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Exo"
url = "app/static/Exo/Exo-VariableFont_wght.ttf"
style="normal"

[[theme.fontFaces]]
family = "Exo"
url = "app/static/Exo/Exo-Italic-VariableFont_wght.ttf"
style="italic"

[theme.light]
primaryColor = "#C74A97"
backgroundColor = "#F1F1F1"
secondaryBackgroundColor = "#DFD9DF"
textColor = "#78547B"
font = "Exo"

[theme.dark]
primaryColor = "#65B8DC"
backgroundColor = "#1C1C1C"
secondaryBackgroundColor = "#2E222F"
textColor = "#BDBCDB"
font = "Exo"

[browser]
gatherUsageStats = false
